### ISSUE TITLE
Root account is lock

### ISSUE THREAD

**Issue by sangeetayadav** [nozaq/amazon-linux-cis#17]
Hi Nozaq,

i applied this cis bechmark rules to Amazon Linux 2 and after applyting i am not able to ssh . 

we are launching an instance with base image as AMAZON LINUX 2 and hardened with CIS benchmarks.  the error is defined " can not open the access to console , root account is locked."

Can you please help us in finding the issue behind this.

**Comment by tgrodzin** [comment]
Hi @sangeetayadav,

this is by intention: https://github.com/nozaq/amazon-linux-cis/blob/2120ea543e42b6fb798120de4e11f2839f1469a1/__main__.py#L415

**Comment by nozaq** [comment]
@sangeetayadav 
Yes, tgrodzin is right. Disallowing root login on SSH is a quite standard way to harden your Linux hosts.
You could create another user to use for daily operations and register that user in the`sudoer` list to allow invoking privileged actions.
